# Generated by Django 4.2.4 on 2023-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estoque",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DataCriacao", models.DateTimeField()),
            ],
            options={
                "db_table": "Estoque",
            },
        ),
    ]
