# Generated by Django 4.2.4 on 2023-08-19 20:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Estoque", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="estoque",
            name="Ativo",
            field=models.BooleanField(default=True),
        ),
    ]
