# Generated by Django 4.2.4 on 2023-08-19 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("Produto", "0002_produto_ativo_produto_preco"),
        ("Estoque", "0002_estoque_ativo"),
    ]

    operations = [
        migrations.AddField(
            model_name="estoque",
            name="Produto",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="Produto.produto",
            ),
        ),
    ]
