# Generated by Django 4.2.4 on 2023-08-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Produto",
            fields=[
                (
                    "Id",
                    models.CharField(max_length=40, primary_key=True, serialize=False),
                ),
                ("Nome", models.CharField(max_length=150)),
                ("Descricao", models.TextField()),
                ("Marca", models.CharField(max_length=100)),
                ("Modelo", models.CharField(max_length=100)),
                ("Sku", models.CharField(max_length=10)),
                ("Ncm", models.CharField(max_length=8)),
                ("Ean", models.CharField(max_length=13)),
                ("Unidade", models.CharField(max_length=5)),
                ("DataCriacao", models.DateTimeField()),
            ],
            options={
                "db_table": "Produto",
            },
        ),
    ]
