# Generated by Django 4.2.4 on 2023-08-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Produto", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produto",
            name="Ativo",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="produto",
            name="Preco",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
